project_id = "hobkkvojjzrbkgcuqfgo"

[functions.generate-forecast]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false

[functions.send-demo-request]
verify_jwt = false

[functions.send-waitlist-request]
verify_jwt = false